camera_adapter:
  ros__parameters:
    input_topic: /zed/zed_node/rgb/color/rect/image
    output_topic: /vla/image_rgb

    output_width: 640
    output_height: 480

    center_crop_square: false
    flip_horizontal: false

    log_every_n_frames: 100

openvla_inference:
  ros__parameters:
    model_path: "/home/ubuntu/robot_ws/src/openvla/runs/47a0ec7fc4ec123775a391911046cf33cf9ed83f+doosan_a0509+b8+lr-0.0005+lora-r32+dropout-0.0--handguide_10hz_resampled--image_aug"

    unnorm_key: "doosan_a0509"

    device: "cuda:0"
    use_flash_attention: true

    default_instruction: "pick up the cube"

    minimum_period_sec: 0.1
    center_crop_scale: 1.0

    do_sample: false
    temperature: 1.0
    top_p: 1.0

    require_robot_cycle: false

    log_image_hash: true
    log_image_statistics: true

    repeat_action_epsilon: 1.0e-5
    repeated_action_warn_count: 3

action_adapter:
  ros__parameters:
    translation_scale_to_mm: 1000.0
    rotation_scale_to_deg: 57.29577951308232

    max_translation_step_mm: 10.0
    max_rotation_step_deg: 3.0

    apply_rotation: false

    gripper_open_threshold: 0.7
    gripper_close_threshold: 0.3

    reject_repeated_actions: false
    repeated_action_limit: 10
    repeat_action_epsilon: 1.0e-5

    max_pose_age_sec: 0.3

    axis_sign: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

    workspace_min: [-100.0, -400.0, 20.0, -360.0, -360.0, -360.0]
    workspace_max: [750.0, 400.0, 700.0, 360.0, 360.0, 360.0]

doosan_bridge:
  ros__parameters:
    robot_namespace: /dsr01

    pose_poll_hz: 20.0

    linear_velocity: [20.0, 10.0]
    linear_acceleration: [40.0, 20.0]

    motion_time_sec: 0.0
    reference: 0
    motion_timeout_sec: 10.0

    # 초기 검증 시 true
    dry_run: true

    gripper_open_output_index: 1
    gripper_close_output_index: 2

    gripper_active_value: 1
    gripper_inactive_value: 0

    gripper_open_pulse_count: 2
    gripper_close_pulse_count: 1
    gripper_pulse_time_sec: 1.0

episode_manager:
  ros__parameters:
    instruction: "pick up the cube"

    # 실제 완료된 MoveLine 횟수
    max_steps: 30

    # robot_ready 이후부터 측정
    max_duration_sec: 60.0

    # 초기 그리퍼 OPEN과 pose 수신 대기 제한
    robot_ready_timeout_sec: 15.0

    # 연속 invalid action 허용 횟수
    invalid_action_limit: 3

    emergency_stop_on_timeout: true
    emergency_stop_on_invalid_action: true
